bin, zsh: Improve venv script
1. Add a -c flag to create or upgrade the venv. When either $arg or
   $arg/.venv is an existing venv, it is used as before. Otherwise .venv
   is created in an existing directory, or $arg is created as a venv if
   it doesn't exist. Symlinks are resolved before creation, so that you
   can link .venv to the desired location of the venv, then run e.g.
   `venv -c . -n pip install ...` to create it without having to specify
   the path again.

2. Eliminate the two separate paths by unconditionally running in a
   sandbox. This also removes the venv indicator from the zsh prompt,
   since the sandbox indicator serves basically the same purpose.

diff --git a/.local/bin/venv b/.local/bin/venv
--- a/.local/bin/venv
+++ b/.local/bin/venv
@@ -1,25 +1,18 @@
 #!/bin/bash
 
+[[ $1 = -c ]] && shift && create=1 || create=0
 arg=${1:-.}
 shift
 
-if [[ -f $arg/pyvenv.cfg ]]; then
-    venv=$arg
-elif [[ -d $arg/.venv ]]; then
-    venv=$arg/.venv
-else
-    echo "error: $arg contains neither pyvenv.cfg nor .venv" >&2
+[[ -f $arg/pyvenv.cfg || ! -d $arg ]] && venv=$arg || venv=$arg/.venv
+venv=$(realpath -m -- "$venv")
+
+if ((create)); then
+    python -m venv -- "$venv" || exit
+elif [[ ! -f $venv/pyvenv.cfg ]]; then
+    echo "error: neither $arg nor $arg/.venv is a virtual environment" >&2
     exit 1
 fi
 
-export VIRTUAL_ENV=$(realpath -- "$venv")
-
-[[ $1 = jupyter-lab ]] && set sb -xur ~/.jupyter/lab/user-settings "$@"
-
-if [[ $1 = sb ]]; then
-    shift
-    exec sb -w ":$arg" -w ":$VIRTUAL_ENV" -e PATH="$VIRTUAL_ENV/bin:$PATH" "$@"
-else
-    (($#)) || set zsh
-    PATH=$VIRTUAL_ENV/bin:$PATH exec "$@"
-fi
+[[ $1 = jupyter-lab ]] && set -- -xur ~/.jupyter/lab/user-settings "$@"
+exec sb -w ":$arg" -w ":$venv" -e VIRTUAL_ENV="$venv" -e PATH="$venv/bin:$PATH" "$@"
