bin: Improve venv scripts
As an alternative to giving the path to the venv, it is now possible to
give the path to a project (default .) that contains a venv named .venv
(the same name used in the LSP setup).

The functionality of the venv-jupyter-lab script has been moved to the
venv and jupyter-lab scripts, and is now accessible by running "venv
<path> jupyter-lab". It still runs in a sandbox (so that the ipykernel
is not installed globally), but it now binds both the project directory
and venv writably, to allow editing notebooks and installing packages.
The sandboxing support seems like it could be useful in other contexts,
so it is now accessible using "venv <path> sandbox <args>".

diff --git a/.local/bin/venv b/.local/bin/venv
--- a/.local/bin/venv
+++ b/.local/bin/venv
@@ -1,6 +1,25 @@
 #!/bin/bash
-set -e
-export VIRTUAL_ENV=$(realpath -e -- "$1")
+
+arg=${1:-.}
 shift
-(($#)) || set zsh
-PATH=$VIRTUAL_ENV/bin:$PATH exec "$@"
+
+if [[ -f $arg/pyvenv.cfg ]]; then
+    venv=$arg
+elif [[ -d $arg/.venv ]]; then
+    venv=$arg/.venv
+else
+    echo "error: $arg contains neither pyvenv.cfg nor .venv" >&2
+    exit 1
+fi
+
+export VIRTUAL_ENV=$(realpath -- "$venv")
+
+[[ $1 = jupyter-lab ]] && set sandbox -xur ~/.jupyter/lab/user-settings "$@"
+
+if [[ $1 = sandbox ]]; then
+    shift
+    exec sandbox -w "$arg" -w "$VIRTUAL_ENV" -e PATH="$VIRTUAL_ENV/bin:$PATH" "$@"
+else
+    (($#)) || set zsh
+    PATH=$VIRTUAL_ENV/bin:$PATH exec "$@"
+fi
